### PR TITLE
base helm chart template

### PR DESCRIPTION
**Pull request by chicco785**
few comments:
* readme must be completed
* few things (e.g. smpt configuration are not configurable in the value.yml)
* tested with gravitee 1.15.0, mongodb 3.2 (version of the helm chart  2.1.4) elk 5.6 (version of the helm chart 0.4.9) 
* some part of the configuration assume usage of ingress services (we tested only with nginx, but of course it should work with other services, configuration may be different from the one in value.yml)

### CODE REVIEW

**Comment by chicco785** [comment]
@PierrickI3 as mentioned it needs clean up and update (i think a number of changes occurred from 1.15.0 to 1.16.0+), i don't have time before august to put my self on this, so if you think this is a good base, we could:

1. merge it as first attempt
1. you or any other contributor can make PR on top of it to improve and complete.

feelings?

**Comment by PierrickI3** [comment]
I agree with first merging it and working off of the master branch for now, to keep it simple.

**Comment by brasseld** [comment]
Ok done!

**Comment by PierrickI3** [comment]
Thanks @brasseld. I've got a conference to attend to tomorrow and Thursday then going back home on Friday. I might have some time on Friday though or I will have to look at this next Monday.

**Comment by jotamorais** [comment]
@chicco785 @PierrickI3 @brasseld, I will start testing now and will keep you posted in case I find something that can be improved. Let me know if you think I can help with something else.

**Comment by PierrickI3** [comment]
Thanks @jotamorais. I managed to deploy Gravitee with yaml files but it's a basic install. I will use the yaml files I created to compare with the chart too, but probably not before next week.

**Comment by PierrickI3** [comment]
@chicco785 and @brasseld , how can you test this helm chart locally? I tried running  helm install https://github.com/gravitee-io/gravitee-kubernetes/tree/master/gravitee but it expects a gzip file.

Sorry, first time I am creating a helm chart and I could not find anywhere on the helm github pages how to test this chart.

**Comment by chicco785** [comment]
sorry @PierrickI3 i was on holidays when you wrote, and your comment got lost in the inbox.

you can just checkout the repository and run helm install passing the path.

**Comment by PierrickI3** [comment]
Thanks @chicco785. I unfortunately had to move on to something else. I might get back to this but not for a while.

**Pull request merged**
